version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: localmssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=true
      - SA_PASSWORD=Password123456789