spring:
  batch:
    jdbc:
      initialize-schema: never # ????DB?????? https://spring.pleiades.io/spring-boot/docs/current/reference/html/howto.html#howto.data-initialization.batch
  ## Local????SQLServer?????
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=false;
    username: sa
    password: Password123456789